// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

/**
 * Protobuf type {@code CartOffer}
 */
public final class CartOffer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CartOffer)
    CartOfferOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CartOffer.newBuilder() to construct.
  private CartOffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CartOffer() {
    username_ = "";
    collectionOption_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CartOffer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CartOffer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            mango.sep3.databaseaccess.protobuf.Offer.Builder subBuilder = null;
            if (offer_ != null) {
              subBuilder = offer_.toBuilder();
            }
            offer_ = input.readMessage(mango.sep3.databaseaccess.protobuf.Offer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(offer_);
              offer_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            quantity_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            collectionOption_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mango.sep3.databaseaccess.protobuf.Contract.internal_static_CartOffer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mango.sep3.databaseaccess.protobuf.Contract.internal_static_CartOffer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mango.sep3.databaseaccess.protobuf.CartOffer.class, mango.sep3.databaseaccess.protobuf.CartOffer.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int OFFER_FIELD_NUMBER = 2;
  private mango.sep3.databaseaccess.protobuf.Offer offer_;
  /**
   * <code>.Offer offer = 2;</code>
   * @return Whether the offer field is set.
   */
  @java.lang.Override
  public boolean hasOffer() {
    return offer_ != null;
  }
  /**
   * <code>.Offer offer = 2;</code>
   * @return The offer.
   */
  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.Offer getOffer() {
    return offer_ == null ? mango.sep3.databaseaccess.protobuf.Offer.getDefaultInstance() : offer_;
  }
  /**
   * <code>.Offer offer = 2;</code>
   */
  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.OfferOrBuilder getOfferOrBuilder() {
    return getOffer();
  }

  public static final int QUANTITY_FIELD_NUMBER = 3;
  private int quantity_;
  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int USERNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 4;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 4;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLLECTIONOPTION_FIELD_NUMBER = 5;
  private volatile java.lang.Object collectionOption_;
  /**
   * <code>string collectionOption = 5;</code>
   * @return The collectionOption.
   */
  @java.lang.Override
  public java.lang.String getCollectionOption() {
    java.lang.Object ref = collectionOption_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      collectionOption_ = s;
      return s;
    }
  }
  /**
   * <code>string collectionOption = 5;</code>
   * @return The bytes for collectionOption.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCollectionOptionBytes() {
    java.lang.Object ref = collectionOption_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      collectionOption_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (offer_ != null) {
      output.writeMessage(2, getOffer());
    }
    if (quantity_ != 0) {
      output.writeInt32(3, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionOption_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, collectionOption_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (offer_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOffer());
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionOption_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, collectionOption_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mango.sep3.databaseaccess.protobuf.CartOffer)) {
      return super.equals(obj);
    }
    mango.sep3.databaseaccess.protobuf.CartOffer other = (mango.sep3.databaseaccess.protobuf.CartOffer) obj;

    if (getId()
        != other.getId()) return false;
    if (hasOffer() != other.hasOffer()) return false;
    if (hasOffer()) {
      if (!getOffer()
          .equals(other.getOffer())) return false;
    }
    if (getQuantity()
        != other.getQuantity()) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getCollectionOption()
        .equals(other.getCollectionOption())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (hasOffer()) {
      hash = (37 * hash) + OFFER_FIELD_NUMBER;
      hash = (53 * hash) + getOffer().hashCode();
    }
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + COLLECTIONOPTION_FIELD_NUMBER;
    hash = (53 * hash) + getCollectionOption().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.CartOffer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mango.sep3.databaseaccess.protobuf.CartOffer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CartOffer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CartOffer)
      mango.sep3.databaseaccess.protobuf.CartOfferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_CartOffer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_CartOffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mango.sep3.databaseaccess.protobuf.CartOffer.class, mango.sep3.databaseaccess.protobuf.CartOffer.Builder.class);
    }

    // Construct using mango.sep3.databaseaccess.protobuf.CartOffer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      if (offerBuilder_ == null) {
        offer_ = null;
      } else {
        offer_ = null;
        offerBuilder_ = null;
      }
      quantity_ = 0;

      username_ = "";

      collectionOption_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_CartOffer_descriptor;
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.CartOffer getDefaultInstanceForType() {
      return mango.sep3.databaseaccess.protobuf.CartOffer.getDefaultInstance();
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.CartOffer build() {
      mango.sep3.databaseaccess.protobuf.CartOffer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.CartOffer buildPartial() {
      mango.sep3.databaseaccess.protobuf.CartOffer result = new mango.sep3.databaseaccess.protobuf.CartOffer(this);
      result.id_ = id_;
      if (offerBuilder_ == null) {
        result.offer_ = offer_;
      } else {
        result.offer_ = offerBuilder_.build();
      }
      result.quantity_ = quantity_;
      result.username_ = username_;
      result.collectionOption_ = collectionOption_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mango.sep3.databaseaccess.protobuf.CartOffer) {
        return mergeFrom((mango.sep3.databaseaccess.protobuf.CartOffer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mango.sep3.databaseaccess.protobuf.CartOffer other) {
      if (other == mango.sep3.databaseaccess.protobuf.CartOffer.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.hasOffer()) {
        mergeOffer(other.getOffer());
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getCollectionOption().isEmpty()) {
        collectionOption_ = other.collectionOption_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mango.sep3.databaseaccess.protobuf.CartOffer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mango.sep3.databaseaccess.protobuf.CartOffer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private mango.sep3.databaseaccess.protobuf.Offer offer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        mango.sep3.databaseaccess.protobuf.Offer, mango.sep3.databaseaccess.protobuf.Offer.Builder, mango.sep3.databaseaccess.protobuf.OfferOrBuilder> offerBuilder_;
    /**
     * <code>.Offer offer = 2;</code>
     * @return Whether the offer field is set.
     */
    public boolean hasOffer() {
      return offerBuilder_ != null || offer_ != null;
    }
    /**
     * <code>.Offer offer = 2;</code>
     * @return The offer.
     */
    public mango.sep3.databaseaccess.protobuf.Offer getOffer() {
      if (offerBuilder_ == null) {
        return offer_ == null ? mango.sep3.databaseaccess.protobuf.Offer.getDefaultInstance() : offer_;
      } else {
        return offerBuilder_.getMessage();
      }
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder setOffer(mango.sep3.databaseaccess.protobuf.Offer value) {
      if (offerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        offer_ = value;
        onChanged();
      } else {
        offerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder setOffer(
        mango.sep3.databaseaccess.protobuf.Offer.Builder builderForValue) {
      if (offerBuilder_ == null) {
        offer_ = builderForValue.build();
        onChanged();
      } else {
        offerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder mergeOffer(mango.sep3.databaseaccess.protobuf.Offer value) {
      if (offerBuilder_ == null) {
        if (offer_ != null) {
          offer_ =
            mango.sep3.databaseaccess.protobuf.Offer.newBuilder(offer_).mergeFrom(value).buildPartial();
        } else {
          offer_ = value;
        }
        onChanged();
      } else {
        offerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder clearOffer() {
      if (offerBuilder_ == null) {
        offer_ = null;
        onChanged();
      } else {
        offer_ = null;
        offerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public mango.sep3.databaseaccess.protobuf.Offer.Builder getOfferBuilder() {
      
      onChanged();
      return getOfferFieldBuilder().getBuilder();
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OfferOrBuilder getOfferOrBuilder() {
      if (offerBuilder_ != null) {
        return offerBuilder_.getMessageOrBuilder();
      } else {
        return offer_ == null ?
            mango.sep3.databaseaccess.protobuf.Offer.getDefaultInstance() : offer_;
      }
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        mango.sep3.databaseaccess.protobuf.Offer, mango.sep3.databaseaccess.protobuf.Offer.Builder, mango.sep3.databaseaccess.protobuf.OfferOrBuilder> 
        getOfferFieldBuilder() {
      if (offerBuilder_ == null) {
        offerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            mango.sep3.databaseaccess.protobuf.Offer, mango.sep3.databaseaccess.protobuf.Offer.Builder, mango.sep3.databaseaccess.protobuf.OfferOrBuilder>(
                getOffer(),
                getParentForChildren(),
                isClean());
        offer_ = null;
      }
      return offerBuilder_;
    }

    private int quantity_ ;
    /**
     * <code>int32 quantity = 3;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>int32 quantity = 3;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      
      quantity_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 4;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 4;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 4;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 4;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object collectionOption_ = "";
    /**
     * <code>string collectionOption = 5;</code>
     * @return The collectionOption.
     */
    public java.lang.String getCollectionOption() {
      java.lang.Object ref = collectionOption_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectionOption_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string collectionOption = 5;</code>
     * @return The bytes for collectionOption.
     */
    public com.google.protobuf.ByteString
        getCollectionOptionBytes() {
      java.lang.Object ref = collectionOption_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectionOption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string collectionOption = 5;</code>
     * @param value The collectionOption to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionOption(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      collectionOption_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string collectionOption = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectionOption() {
      
      collectionOption_ = getDefaultInstance().getCollectionOption();
      onChanged();
      return this;
    }
    /**
     * <code>string collectionOption = 5;</code>
     * @param value The bytes for collectionOption to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionOptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      collectionOption_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CartOffer)
  }

  // @@protoc_insertion_point(class_scope:CartOffer)
  private static final mango.sep3.databaseaccess.protobuf.CartOffer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mango.sep3.databaseaccess.protobuf.CartOffer();
  }

  public static mango.sep3.databaseaccess.protobuf.CartOffer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CartOffer>
      PARSER = new com.google.protobuf.AbstractParser<CartOffer>() {
    @java.lang.Override
    public CartOffer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CartOffer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CartOffer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CartOffer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.CartOffer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

