// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

public final class Contract {
  private Contract() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Farm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Farm_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Offer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Offer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfferItems_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfferItems_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Void_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Void_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CartOffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CartOffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CartOffers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CartOffers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Username_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Username_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contract.proto\"\253\001\n\004Farm\022\014\n\004name\030\001 \001(\t\022" +
      "\r\n\005phone\030\002 \001(\t\022\013\n\003zip\030\003 \001(\t\022\017\n\007address\030\004" +
      " \001(\t\022\014\n\004city\030\005 \001(\t\022\027\n\nfarmStatus\030\006 \001(\tH\000" +
      "\210\001\001\022\035\n\020deliveryDistance\030\007 \001(\005H\001\210\001\001B\r\n\013_f" +
      "armStatusB\023\n\021_deliveryDistance\"\304\001\n\005Offer" +
      "\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010quantity\030\003" +
      " \001(\005\022\014\n\004unit\030\004 \001(\t\022\r\n\005price\030\005 \001(\001\022\020\n\010del" +
      "ivery\030\006 \001(\010\022\016\n\006pickUp\030\007 \001(\010\022\023\n\013pickYourO" +
      "wn\030\010 \001(\010\022\030\n\013description\030\t \001(\tH\000\210\001\001\022\021\n\tIm" +
      "agePath\030\n \001(\tB\016\n\014_description\"$\n\nOfferIt" +
      "ems\022\026\n\006offers\030\001 \003(\0132\006.Offer\"\006\n\004Void\"l\n\tC" +
      "artOffer\022\n\n\002id\030\001 \001(\005\022\025\n\005offer\030\002 \001(\0132\006.Of" +
      "fer\022\020\n\010quantity\030\003 \001(\005\022\020\n\010username\030\004 \001(\t\022" +
      "\030\n\020collectionOption\030\005 \001(\t\",\n\nCartOffers\022" +
      "\036\n\ncartOffers\030\001 \003(\0132\n.CartOffer\"\034\n\010Usern" +
      "ame\022\020\n\010username\030\001 \001(\t2)\n\013FarmService\022\032\n\n" +
      "CreateFarm\022\005.Farm\032\005.Farm2N\n\014OfferService" +
      "\022\035\n\013CreateOffer\022\006.Offer\032\006.Offer\022\037\n\tGetOf" +
      "fers\022\005.Void\032\013.OfferItems2\207\001\n\020CartOfferSe" +
      "rvice\022\036\n\tAddToCart\022\n.CartOffer\032\005.Void\022*\n" +
      "\020GetAllCartOffers\022\t.Username\032\013.CartOffer" +
      "s\022\'\n\023DeleteAllCartOffers\022\t.Username\032\005.Vo" +
      "idB&\n\"mango.sep3.databaseaccess.protobuf" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Farm_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Farm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Farm_descriptor,
        new java.lang.String[] { "Name", "Phone", "Zip", "Address", "City", "FarmStatus", "DeliveryDistance", "FarmStatus", "DeliveryDistance", });
    internal_static_Offer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Offer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Offer_descriptor,
        new java.lang.String[] { "Id", "Name", "Quantity", "Unit", "Price", "Delivery", "PickUp", "PickYourOwn", "Description", "ImagePath", "Description", });
    internal_static_OfferItems_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OfferItems_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfferItems_descriptor,
        new java.lang.String[] { "Offers", });
    internal_static_Void_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Void_descriptor,
        new java.lang.String[] { });
    internal_static_CartOffer_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CartOffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CartOffer_descriptor,
        new java.lang.String[] { "Id", "Offer", "Quantity", "Username", "CollectionOption", });
    internal_static_CartOffers_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CartOffers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CartOffers_descriptor,
        new java.lang.String[] { "CartOffers", });
    internal_static_Username_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Username_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Username_descriptor,
        new java.lang.String[] { "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
