// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

public interface FarmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Farm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Address address = 2;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.Address address = 2;</code>
   * @return The address.
   */
  mango.sep3.databaseaccess.protobuf.Address getAddress();
  /**
   * <code>.Address address = 2;</code>
   */
  mango.sep3.databaseaccess.protobuf.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>.Farmer farmer = 3;</code>
   * @return Whether the farmer field is set.
   */
  boolean hasFarmer();
  /**
   * <code>.Farmer farmer = 3;</code>
   * @return The farmer.
   */
  mango.sep3.databaseaccess.protobuf.Farmer getFarmer();
  /**
   * <code>.Farmer farmer = 3;</code>
   */
  mango.sep3.databaseaccess.protobuf.FarmerOrBuilder getFarmerOrBuilder();

  /**
   * <code>string city = 4;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 4;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>optional string farmStatus = 5;</code>
   * @return Whether the farmStatus field is set.
   */
  boolean hasFarmStatus();
  /**
   * <code>optional string farmStatus = 5;</code>
   * @return The farmStatus.
   */
  java.lang.String getFarmStatus();
  /**
   * <code>optional string farmStatus = 5;</code>
   * @return The bytes for farmStatus.
   */
  com.google.protobuf.ByteString
      getFarmStatusBytes();

  /**
   * <code>optional int32 deliveryDistance = 6;</code>
   * @return Whether the deliveryDistance field is set.
   */
  boolean hasDeliveryDistance();
  /**
   * <code>optional int32 deliveryDistance = 6;</code>
   * @return The deliveryDistance.
   */
  int getDeliveryDistance();

  /**
   * <code>string phone = 7;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 7;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
