// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

public interface OfferItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfferItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  java.util.List<mango.sep3.databaseaccess.protobuf.Offer> 
      getOffersList();
  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  mango.sep3.databaseaccess.protobuf.Offer getOffers(int index);
  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  int getOffersCount();
  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  java.util.List<? extends mango.sep3.databaseaccess.protobuf.OfferOrBuilder> 
      getOffersOrBuilderList();
  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  mango.sep3.databaseaccess.protobuf.OfferOrBuilder getOffersOrBuilder(
      int index);
}
