// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

public interface OfferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Offer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string unit = 4;</code>
   * @return The unit.
   */
  java.lang.String getUnit();
  /**
   * <code>string unit = 4;</code>
   * @return The bytes for unit.
   */
  com.google.protobuf.ByteString
      getUnitBytes();

  /**
   * <code>double price = 5;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>bool delivery = 6;</code>
   * @return The delivery.
   */
  boolean getDelivery();

  /**
   * <code>bool pickUp = 7;</code>
   * @return The pickUp.
   */
  boolean getPickUp();

  /**
   * <code>bool pickYourOwn = 8;</code>
   * @return The pickYourOwn.
   */
  boolean getPickYourOwn();

  /**
   * <code>optional string description = 9;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 9;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 9;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string ImagePath = 10;</code>
   * @return The imagePath.
   */
  java.lang.String getImagePath();
  /**
   * <code>string ImagePath = 10;</code>
   * @return The bytes for imagePath.
   */
  com.google.protobuf.ByteString
      getImagePathBytes();
}
