// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

/**
 * Protobuf type {@code OfferItems}
 */
public final class OfferItems extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OfferItems)
    OfferItemsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OfferItems.newBuilder() to construct.
  private OfferItems(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OfferItems() {
    offers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OfferItems();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OfferItems(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              offers_ = new java.util.ArrayList<mango.sep3.databaseaccess.protobuf.Offer>();
              mutable_bitField0_ |= 0x00000001;
            }
            offers_.add(
                input.readMessage(mango.sep3.databaseaccess.protobuf.Offer.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        offers_ = java.util.Collections.unmodifiableList(offers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OfferItems_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OfferItems_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mango.sep3.databaseaccess.protobuf.OfferItems.class, mango.sep3.databaseaccess.protobuf.OfferItems.Builder.class);
  }

  public static final int OFFERS_FIELD_NUMBER = 1;
  private java.util.List<mango.sep3.databaseaccess.protobuf.Offer> offers_;
  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<mango.sep3.databaseaccess.protobuf.Offer> getOffersList() {
    return offers_;
  }
  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends mango.sep3.databaseaccess.protobuf.OfferOrBuilder> 
      getOffersOrBuilderList() {
    return offers_;
  }
  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  @java.lang.Override
  public int getOffersCount() {
    return offers_.size();
  }
  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.Offer getOffers(int index) {
    return offers_.get(index);
  }
  /**
   * <code>repeated .Offer offers = 1;</code>
   */
  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.OfferOrBuilder getOffersOrBuilder(
      int index) {
    return offers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < offers_.size(); i++) {
      output.writeMessage(1, offers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < offers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, offers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mango.sep3.databaseaccess.protobuf.OfferItems)) {
      return super.equals(obj);
    }
    mango.sep3.databaseaccess.protobuf.OfferItems other = (mango.sep3.databaseaccess.protobuf.OfferItems) obj;

    if (!getOffersList()
        .equals(other.getOffersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOffersCount() > 0) {
      hash = (37 * hash) + OFFERS_FIELD_NUMBER;
      hash = (53 * hash) + getOffersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.OfferItems parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mango.sep3.databaseaccess.protobuf.OfferItems prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OfferItems}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OfferItems)
      mango.sep3.databaseaccess.protobuf.OfferItemsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OfferItems_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OfferItems_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mango.sep3.databaseaccess.protobuf.OfferItems.class, mango.sep3.databaseaccess.protobuf.OfferItems.Builder.class);
    }

    // Construct using mango.sep3.databaseaccess.protobuf.OfferItems.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOffersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (offersBuilder_ == null) {
        offers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        offersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OfferItems_descriptor;
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.OfferItems getDefaultInstanceForType() {
      return mango.sep3.databaseaccess.protobuf.OfferItems.getDefaultInstance();
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.OfferItems build() {
      mango.sep3.databaseaccess.protobuf.OfferItems result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.OfferItems buildPartial() {
      mango.sep3.databaseaccess.protobuf.OfferItems result = new mango.sep3.databaseaccess.protobuf.OfferItems(this);
      int from_bitField0_ = bitField0_;
      if (offersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          offers_ = java.util.Collections.unmodifiableList(offers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.offers_ = offers_;
      } else {
        result.offers_ = offersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mango.sep3.databaseaccess.protobuf.OfferItems) {
        return mergeFrom((mango.sep3.databaseaccess.protobuf.OfferItems)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mango.sep3.databaseaccess.protobuf.OfferItems other) {
      if (other == mango.sep3.databaseaccess.protobuf.OfferItems.getDefaultInstance()) return this;
      if (offersBuilder_ == null) {
        if (!other.offers_.isEmpty()) {
          if (offers_.isEmpty()) {
            offers_ = other.offers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOffersIsMutable();
            offers_.addAll(other.offers_);
          }
          onChanged();
        }
      } else {
        if (!other.offers_.isEmpty()) {
          if (offersBuilder_.isEmpty()) {
            offersBuilder_.dispose();
            offersBuilder_ = null;
            offers_ = other.offers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            offersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOffersFieldBuilder() : null;
          } else {
            offersBuilder_.addAllMessages(other.offers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mango.sep3.databaseaccess.protobuf.OfferItems parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mango.sep3.databaseaccess.protobuf.OfferItems) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<mango.sep3.databaseaccess.protobuf.Offer> offers_ =
      java.util.Collections.emptyList();
    private void ensureOffersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        offers_ = new java.util.ArrayList<mango.sep3.databaseaccess.protobuf.Offer>(offers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        mango.sep3.databaseaccess.protobuf.Offer, mango.sep3.databaseaccess.protobuf.Offer.Builder, mango.sep3.databaseaccess.protobuf.OfferOrBuilder> offersBuilder_;

    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public java.util.List<mango.sep3.databaseaccess.protobuf.Offer> getOffersList() {
      if (offersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(offers_);
      } else {
        return offersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public int getOffersCount() {
      if (offersBuilder_ == null) {
        return offers_.size();
      } else {
        return offersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.Offer getOffers(int index) {
      if (offersBuilder_ == null) {
        return offers_.get(index);
      } else {
        return offersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public Builder setOffers(
        int index, mango.sep3.databaseaccess.protobuf.Offer value) {
      if (offersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffersIsMutable();
        offers_.set(index, value);
        onChanged();
      } else {
        offersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public Builder setOffers(
        int index, mango.sep3.databaseaccess.protobuf.Offer.Builder builderForValue) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        offers_.set(index, builderForValue.build());
        onChanged();
      } else {
        offersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public Builder addOffers(mango.sep3.databaseaccess.protobuf.Offer value) {
      if (offersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffersIsMutable();
        offers_.add(value);
        onChanged();
      } else {
        offersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public Builder addOffers(
        int index, mango.sep3.databaseaccess.protobuf.Offer value) {
      if (offersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffersIsMutable();
        offers_.add(index, value);
        onChanged();
      } else {
        offersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public Builder addOffers(
        mango.sep3.databaseaccess.protobuf.Offer.Builder builderForValue) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        offers_.add(builderForValue.build());
        onChanged();
      } else {
        offersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public Builder addOffers(
        int index, mango.sep3.databaseaccess.protobuf.Offer.Builder builderForValue) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        offers_.add(index, builderForValue.build());
        onChanged();
      } else {
        offersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public Builder addAllOffers(
        java.lang.Iterable<? extends mango.sep3.databaseaccess.protobuf.Offer> values) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, offers_);
        onChanged();
      } else {
        offersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public Builder clearOffers() {
      if (offersBuilder_ == null) {
        offers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        offersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public Builder removeOffers(int index) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        offers_.remove(index);
        onChanged();
      } else {
        offersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.Offer.Builder getOffersBuilder(
        int index) {
      return getOffersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OfferOrBuilder getOffersOrBuilder(
        int index) {
      if (offersBuilder_ == null) {
        return offers_.get(index);  } else {
        return offersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public java.util.List<? extends mango.sep3.databaseaccess.protobuf.OfferOrBuilder> 
         getOffersOrBuilderList() {
      if (offersBuilder_ != null) {
        return offersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(offers_);
      }
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.Offer.Builder addOffersBuilder() {
      return getOffersFieldBuilder().addBuilder(
          mango.sep3.databaseaccess.protobuf.Offer.getDefaultInstance());
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.Offer.Builder addOffersBuilder(
        int index) {
      return getOffersFieldBuilder().addBuilder(
          index, mango.sep3.databaseaccess.protobuf.Offer.getDefaultInstance());
    }
    /**
     * <code>repeated .Offer offers = 1;</code>
     */
    public java.util.List<mango.sep3.databaseaccess.protobuf.Offer.Builder> 
         getOffersBuilderList() {
      return getOffersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        mango.sep3.databaseaccess.protobuf.Offer, mango.sep3.databaseaccess.protobuf.Offer.Builder, mango.sep3.databaseaccess.protobuf.OfferOrBuilder> 
        getOffersFieldBuilder() {
      if (offersBuilder_ == null) {
        offersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            mango.sep3.databaseaccess.protobuf.Offer, mango.sep3.databaseaccess.protobuf.Offer.Builder, mango.sep3.databaseaccess.protobuf.OfferOrBuilder>(
                offers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        offers_ = null;
      }
      return offersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OfferItems)
  }

  // @@protoc_insertion_point(class_scope:OfferItems)
  private static final mango.sep3.databaseaccess.protobuf.OfferItems DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mango.sep3.databaseaccess.protobuf.OfferItems();
  }

  public static mango.sep3.databaseaccess.protobuf.OfferItems getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OfferItems>
      PARSER = new com.google.protobuf.AbstractParser<OfferItems>() {
    @java.lang.Override
    public OfferItems parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OfferItems(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OfferItems> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OfferItems> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.OfferItems getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

