// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

/**
 * Protobuf type {@code Order}
 */
public final class Order extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Order)
    OrderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Order.newBuilder() to construct.
  private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Order() {
    orderOffers_ = java.util.Collections.emptyList();
    farmName_ = "";
    collectionOption_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Order();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Order(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              orderOffers_ = new java.util.ArrayList<mango.sep3.databaseaccess.protobuf.OrderOffer>();
              mutable_bitField0_ |= 0x00000001;
            }
            orderOffers_.add(
                input.readMessage(mango.sep3.databaseaccess.protobuf.OrderOffer.parser(), extensionRegistry));
            break;
          }
          case 24: {

            isDone_ = input.readBool();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            farmName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            collectionOption_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        orderOffers_ = java.util.Collections.unmodifiableList(orderOffers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mango.sep3.databaseaccess.protobuf.Contract.internal_static_Order_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mango.sep3.databaseaccess.protobuf.Contract.internal_static_Order_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mango.sep3.databaseaccess.protobuf.Order.class, mango.sep3.databaseaccess.protobuf.Order.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int ORDEROFFERS_FIELD_NUMBER = 2;
  private java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer> orderOffers_;
  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer> getOrderOffersList() {
    return orderOffers_;
  }
  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder> 
      getOrderOffersOrBuilderList() {
    return orderOffers_;
  }
  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  @java.lang.Override
  public int getOrderOffersCount() {
    return orderOffers_.size();
  }
  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.OrderOffer getOrderOffers(int index) {
    return orderOffers_.get(index);
  }
  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder getOrderOffersOrBuilder(
      int index) {
    return orderOffers_.get(index);
  }

  public static final int ISDONE_FIELD_NUMBER = 3;
  private boolean isDone_;
  /**
   * <code>bool isDone = 3;</code>
   * @return The isDone.
   */
  @java.lang.Override
  public boolean getIsDone() {
    return isDone_;
  }

  public static final int FARMNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object farmName_;
  /**
   * <code>string farmName = 4;</code>
   * @return The farmName.
   */
  @java.lang.Override
  public java.lang.String getFarmName() {
    java.lang.Object ref = farmName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      farmName_ = s;
      return s;
    }
  }
  /**
   * <code>string farmName = 4;</code>
   * @return The bytes for farmName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFarmNameBytes() {
    java.lang.Object ref = farmName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      farmName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLLECTIONOPTION_FIELD_NUMBER = 5;
  private volatile java.lang.Object collectionOption_;
  /**
   * <code>string collectionOption = 5;</code>
   * @return The collectionOption.
   */
  @java.lang.Override
  public java.lang.String getCollectionOption() {
    java.lang.Object ref = collectionOption_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      collectionOption_ = s;
      return s;
    }
  }
  /**
   * <code>string collectionOption = 5;</code>
   * @return The bytes for collectionOption.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCollectionOptionBytes() {
    java.lang.Object ref = collectionOption_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      collectionOption_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    for (int i = 0; i < orderOffers_.size(); i++) {
      output.writeMessage(2, orderOffers_.get(i));
    }
    if (isDone_ != false) {
      output.writeBool(3, isDone_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(farmName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, farmName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionOption_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, collectionOption_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    for (int i = 0; i < orderOffers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, orderOffers_.get(i));
    }
    if (isDone_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isDone_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(farmName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, farmName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionOption_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, collectionOption_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mango.sep3.databaseaccess.protobuf.Order)) {
      return super.equals(obj);
    }
    mango.sep3.databaseaccess.protobuf.Order other = (mango.sep3.databaseaccess.protobuf.Order) obj;

    if (getId()
        != other.getId()) return false;
    if (!getOrderOffersList()
        .equals(other.getOrderOffersList())) return false;
    if (getIsDone()
        != other.getIsDone()) return false;
    if (!getFarmName()
        .equals(other.getFarmName())) return false;
    if (!getCollectionOption()
        .equals(other.getCollectionOption())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (getOrderOffersCount() > 0) {
      hash = (37 * hash) + ORDEROFFERS_FIELD_NUMBER;
      hash = (53 * hash) + getOrderOffersList().hashCode();
    }
    hash = (37 * hash) + ISDONE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDone());
    hash = (37 * hash) + FARMNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFarmName().hashCode();
    hash = (37 * hash) + COLLECTIONOPTION_FIELD_NUMBER;
    hash = (53 * hash) + getCollectionOption().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.Order parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mango.sep3.databaseaccess.protobuf.Order prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Order}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Order)
      mango.sep3.databaseaccess.protobuf.OrderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mango.sep3.databaseaccess.protobuf.Order.class, mango.sep3.databaseaccess.protobuf.Order.Builder.class);
    }

    // Construct using mango.sep3.databaseaccess.protobuf.Order.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOrderOffersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      if (orderOffersBuilder_ == null) {
        orderOffers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        orderOffersBuilder_.clear();
      }
      isDone_ = false;

      farmName_ = "";

      collectionOption_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_Order_descriptor;
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.Order getDefaultInstanceForType() {
      return mango.sep3.databaseaccess.protobuf.Order.getDefaultInstance();
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.Order build() {
      mango.sep3.databaseaccess.protobuf.Order result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.Order buildPartial() {
      mango.sep3.databaseaccess.protobuf.Order result = new mango.sep3.databaseaccess.protobuf.Order(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (orderOffersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          orderOffers_ = java.util.Collections.unmodifiableList(orderOffers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.orderOffers_ = orderOffers_;
      } else {
        result.orderOffers_ = orderOffersBuilder_.build();
      }
      result.isDone_ = isDone_;
      result.farmName_ = farmName_;
      result.collectionOption_ = collectionOption_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mango.sep3.databaseaccess.protobuf.Order) {
        return mergeFrom((mango.sep3.databaseaccess.protobuf.Order)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mango.sep3.databaseaccess.protobuf.Order other) {
      if (other == mango.sep3.databaseaccess.protobuf.Order.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (orderOffersBuilder_ == null) {
        if (!other.orderOffers_.isEmpty()) {
          if (orderOffers_.isEmpty()) {
            orderOffers_ = other.orderOffers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOrderOffersIsMutable();
            orderOffers_.addAll(other.orderOffers_);
          }
          onChanged();
        }
      } else {
        if (!other.orderOffers_.isEmpty()) {
          if (orderOffersBuilder_.isEmpty()) {
            orderOffersBuilder_.dispose();
            orderOffersBuilder_ = null;
            orderOffers_ = other.orderOffers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            orderOffersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderOffersFieldBuilder() : null;
          } else {
            orderOffersBuilder_.addAllMessages(other.orderOffers_);
          }
        }
      }
      if (other.getIsDone() != false) {
        setIsDone(other.getIsDone());
      }
      if (!other.getFarmName().isEmpty()) {
        farmName_ = other.farmName_;
        onChanged();
      }
      if (!other.getCollectionOption().isEmpty()) {
        collectionOption_ = other.collectionOption_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mango.sep3.databaseaccess.protobuf.Order parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mango.sep3.databaseaccess.protobuf.Order) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer> orderOffers_ =
      java.util.Collections.emptyList();
    private void ensureOrderOffersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        orderOffers_ = new java.util.ArrayList<mango.sep3.databaseaccess.protobuf.OrderOffer>(orderOffers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        mango.sep3.databaseaccess.protobuf.OrderOffer, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder, mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder> orderOffersBuilder_;

    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer> getOrderOffersList() {
      if (orderOffersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderOffers_);
      } else {
        return orderOffersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public int getOrderOffersCount() {
      if (orderOffersBuilder_ == null) {
        return orderOffers_.size();
      } else {
        return orderOffersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOffer getOrderOffers(int index) {
      if (orderOffersBuilder_ == null) {
        return orderOffers_.get(index);
      } else {
        return orderOffersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public Builder setOrderOffers(
        int index, mango.sep3.databaseaccess.protobuf.OrderOffer value) {
      if (orderOffersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderOffersIsMutable();
        orderOffers_.set(index, value);
        onChanged();
      } else {
        orderOffersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public Builder setOrderOffers(
        int index, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder builderForValue) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        orderOffers_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderOffersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public Builder addOrderOffers(mango.sep3.databaseaccess.protobuf.OrderOffer value) {
      if (orderOffersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderOffersIsMutable();
        orderOffers_.add(value);
        onChanged();
      } else {
        orderOffersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public Builder addOrderOffers(
        int index, mango.sep3.databaseaccess.protobuf.OrderOffer value) {
      if (orderOffersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderOffersIsMutable();
        orderOffers_.add(index, value);
        onChanged();
      } else {
        orderOffersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public Builder addOrderOffers(
        mango.sep3.databaseaccess.protobuf.OrderOffer.Builder builderForValue) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        orderOffers_.add(builderForValue.build());
        onChanged();
      } else {
        orderOffersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public Builder addOrderOffers(
        int index, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder builderForValue) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        orderOffers_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderOffersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public Builder addAllOrderOffers(
        java.lang.Iterable<? extends mango.sep3.databaseaccess.protobuf.OrderOffer> values) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderOffers_);
        onChanged();
      } else {
        orderOffersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public Builder clearOrderOffers() {
      if (orderOffersBuilder_ == null) {
        orderOffers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        orderOffersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public Builder removeOrderOffers(int index) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        orderOffers_.remove(index);
        onChanged();
      } else {
        orderOffersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOffer.Builder getOrderOffersBuilder(
        int index) {
      return getOrderOffersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder getOrderOffersOrBuilder(
        int index) {
      if (orderOffersBuilder_ == null) {
        return orderOffers_.get(index);  } else {
        return orderOffersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public java.util.List<? extends mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder> 
         getOrderOffersOrBuilderList() {
      if (orderOffersBuilder_ != null) {
        return orderOffersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderOffers_);
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOffer.Builder addOrderOffersBuilder() {
      return getOrderOffersFieldBuilder().addBuilder(
          mango.sep3.databaseaccess.protobuf.OrderOffer.getDefaultInstance());
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOffer.Builder addOrderOffersBuilder(
        int index) {
      return getOrderOffersFieldBuilder().addBuilder(
          index, mango.sep3.databaseaccess.protobuf.OrderOffer.getDefaultInstance());
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 2;</code>
     */
    public java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer.Builder> 
         getOrderOffersBuilderList() {
      return getOrderOffersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        mango.sep3.databaseaccess.protobuf.OrderOffer, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder, mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder> 
        getOrderOffersFieldBuilder() {
      if (orderOffersBuilder_ == null) {
        orderOffersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            mango.sep3.databaseaccess.protobuf.OrderOffer, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder, mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder>(
                orderOffers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        orderOffers_ = null;
      }
      return orderOffersBuilder_;
    }

    private boolean isDone_ ;
    /**
     * <code>bool isDone = 3;</code>
     * @return The isDone.
     */
    @java.lang.Override
    public boolean getIsDone() {
      return isDone_;
    }
    /**
     * <code>bool isDone = 3;</code>
     * @param value The isDone to set.
     * @return This builder for chaining.
     */
    public Builder setIsDone(boolean value) {
      
      isDone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isDone = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDone() {
      
      isDone_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object farmName_ = "";
    /**
     * <code>string farmName = 4;</code>
     * @return The farmName.
     */
    public java.lang.String getFarmName() {
      java.lang.Object ref = farmName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        farmName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string farmName = 4;</code>
     * @return The bytes for farmName.
     */
    public com.google.protobuf.ByteString
        getFarmNameBytes() {
      java.lang.Object ref = farmName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        farmName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string farmName = 4;</code>
     * @param value The farmName to set.
     * @return This builder for chaining.
     */
    public Builder setFarmName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      farmName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string farmName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFarmName() {
      
      farmName_ = getDefaultInstance().getFarmName();
      onChanged();
      return this;
    }
    /**
     * <code>string farmName = 4;</code>
     * @param value The bytes for farmName to set.
     * @return This builder for chaining.
     */
    public Builder setFarmNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      farmName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object collectionOption_ = "";
    /**
     * <code>string collectionOption = 5;</code>
     * @return The collectionOption.
     */
    public java.lang.String getCollectionOption() {
      java.lang.Object ref = collectionOption_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectionOption_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string collectionOption = 5;</code>
     * @return The bytes for collectionOption.
     */
    public com.google.protobuf.ByteString
        getCollectionOptionBytes() {
      java.lang.Object ref = collectionOption_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectionOption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string collectionOption = 5;</code>
     * @param value The collectionOption to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionOption(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      collectionOption_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string collectionOption = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectionOption() {
      
      collectionOption_ = getDefaultInstance().getCollectionOption();
      onChanged();
      return this;
    }
    /**
     * <code>string collectionOption = 5;</code>
     * @param value The bytes for collectionOption to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionOptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      collectionOption_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Order)
  }

  // @@protoc_insertion_point(class_scope:Order)
  private static final mango.sep3.databaseaccess.protobuf.Order DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mango.sep3.databaseaccess.protobuf.Order();
  }

  public static mango.sep3.databaseaccess.protobuf.Order getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Order>
      PARSER = new com.google.protobuf.AbstractParser<Order>() {
    @java.lang.Override
    public Order parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Order(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Order> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Order> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.Order getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

