// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

/**
 * Protobuf type {@code OrderOffers}
 */
public final class OrderOffers extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OrderOffers)
    OrderOffersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderOffers.newBuilder() to construct.
  private OrderOffers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderOffers() {
    orderOffers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderOffers();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderOffers(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              orderOffers_ = new java.util.ArrayList<mango.sep3.databaseaccess.protobuf.OrderOffer>();
              mutable_bitField0_ |= 0x00000001;
            }
            orderOffers_.add(
                input.readMessage(mango.sep3.databaseaccess.protobuf.OrderOffer.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        orderOffers_ = java.util.Collections.unmodifiableList(orderOffers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OrderOffers_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OrderOffers_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mango.sep3.databaseaccess.protobuf.OrderOffers.class, mango.sep3.databaseaccess.protobuf.OrderOffers.Builder.class);
  }

  public static final int ORDEROFFERS_FIELD_NUMBER = 1;
  private java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer> orderOffers_;
  /**
   * <code>repeated .OrderOffer orderOffers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer> getOrderOffersList() {
    return orderOffers_;
  }
  /**
   * <code>repeated .OrderOffer orderOffers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder> 
      getOrderOffersOrBuilderList() {
    return orderOffers_;
  }
  /**
   * <code>repeated .OrderOffer orderOffers = 1;</code>
   */
  @java.lang.Override
  public int getOrderOffersCount() {
    return orderOffers_.size();
  }
  /**
   * <code>repeated .OrderOffer orderOffers = 1;</code>
   */
  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.OrderOffer getOrderOffers(int index) {
    return orderOffers_.get(index);
  }
  /**
   * <code>repeated .OrderOffer orderOffers = 1;</code>
   */
  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder getOrderOffersOrBuilder(
      int index) {
    return orderOffers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < orderOffers_.size(); i++) {
      output.writeMessage(1, orderOffers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < orderOffers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, orderOffers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mango.sep3.databaseaccess.protobuf.OrderOffers)) {
      return super.equals(obj);
    }
    mango.sep3.databaseaccess.protobuf.OrderOffers other = (mango.sep3.databaseaccess.protobuf.OrderOffers) obj;

    if (!getOrderOffersList()
        .equals(other.getOrderOffersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOrderOffersCount() > 0) {
      hash = (37 * hash) + ORDEROFFERS_FIELD_NUMBER;
      hash = (53 * hash) + getOrderOffersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mango.sep3.databaseaccess.protobuf.OrderOffers parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mango.sep3.databaseaccess.protobuf.OrderOffers prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OrderOffers}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OrderOffers)
      mango.sep3.databaseaccess.protobuf.OrderOffersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OrderOffers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OrderOffers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mango.sep3.databaseaccess.protobuf.OrderOffers.class, mango.sep3.databaseaccess.protobuf.OrderOffers.Builder.class);
    }

    // Construct using mango.sep3.databaseaccess.protobuf.OrderOffers.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOrderOffersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (orderOffersBuilder_ == null) {
        orderOffers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        orderOffersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mango.sep3.databaseaccess.protobuf.Contract.internal_static_OrderOffers_descriptor;
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.OrderOffers getDefaultInstanceForType() {
      return mango.sep3.databaseaccess.protobuf.OrderOffers.getDefaultInstance();
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.OrderOffers build() {
      mango.sep3.databaseaccess.protobuf.OrderOffers result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public mango.sep3.databaseaccess.protobuf.OrderOffers buildPartial() {
      mango.sep3.databaseaccess.protobuf.OrderOffers result = new mango.sep3.databaseaccess.protobuf.OrderOffers(this);
      int from_bitField0_ = bitField0_;
      if (orderOffersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          orderOffers_ = java.util.Collections.unmodifiableList(orderOffers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.orderOffers_ = orderOffers_;
      } else {
        result.orderOffers_ = orderOffersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mango.sep3.databaseaccess.protobuf.OrderOffers) {
        return mergeFrom((mango.sep3.databaseaccess.protobuf.OrderOffers)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mango.sep3.databaseaccess.protobuf.OrderOffers other) {
      if (other == mango.sep3.databaseaccess.protobuf.OrderOffers.getDefaultInstance()) return this;
      if (orderOffersBuilder_ == null) {
        if (!other.orderOffers_.isEmpty()) {
          if (orderOffers_.isEmpty()) {
            orderOffers_ = other.orderOffers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOrderOffersIsMutable();
            orderOffers_.addAll(other.orderOffers_);
          }
          onChanged();
        }
      } else {
        if (!other.orderOffers_.isEmpty()) {
          if (orderOffersBuilder_.isEmpty()) {
            orderOffersBuilder_.dispose();
            orderOffersBuilder_ = null;
            orderOffers_ = other.orderOffers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            orderOffersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderOffersFieldBuilder() : null;
          } else {
            orderOffersBuilder_.addAllMessages(other.orderOffers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mango.sep3.databaseaccess.protobuf.OrderOffers parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mango.sep3.databaseaccess.protobuf.OrderOffers) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer> orderOffers_ =
      java.util.Collections.emptyList();
    private void ensureOrderOffersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        orderOffers_ = new java.util.ArrayList<mango.sep3.databaseaccess.protobuf.OrderOffer>(orderOffers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        mango.sep3.databaseaccess.protobuf.OrderOffer, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder, mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder> orderOffersBuilder_;

    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer> getOrderOffersList() {
      if (orderOffersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderOffers_);
      } else {
        return orderOffersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public int getOrderOffersCount() {
      if (orderOffersBuilder_ == null) {
        return orderOffers_.size();
      } else {
        return orderOffersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOffer getOrderOffers(int index) {
      if (orderOffersBuilder_ == null) {
        return orderOffers_.get(index);
      } else {
        return orderOffersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public Builder setOrderOffers(
        int index, mango.sep3.databaseaccess.protobuf.OrderOffer value) {
      if (orderOffersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderOffersIsMutable();
        orderOffers_.set(index, value);
        onChanged();
      } else {
        orderOffersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public Builder setOrderOffers(
        int index, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder builderForValue) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        orderOffers_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderOffersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public Builder addOrderOffers(mango.sep3.databaseaccess.protobuf.OrderOffer value) {
      if (orderOffersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderOffersIsMutable();
        orderOffers_.add(value);
        onChanged();
      } else {
        orderOffersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public Builder addOrderOffers(
        int index, mango.sep3.databaseaccess.protobuf.OrderOffer value) {
      if (orderOffersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderOffersIsMutable();
        orderOffers_.add(index, value);
        onChanged();
      } else {
        orderOffersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public Builder addOrderOffers(
        mango.sep3.databaseaccess.protobuf.OrderOffer.Builder builderForValue) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        orderOffers_.add(builderForValue.build());
        onChanged();
      } else {
        orderOffersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public Builder addOrderOffers(
        int index, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder builderForValue) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        orderOffers_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderOffersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public Builder addAllOrderOffers(
        java.lang.Iterable<? extends mango.sep3.databaseaccess.protobuf.OrderOffer> values) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderOffers_);
        onChanged();
      } else {
        orderOffersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public Builder clearOrderOffers() {
      if (orderOffersBuilder_ == null) {
        orderOffers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        orderOffersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public Builder removeOrderOffers(int index) {
      if (orderOffersBuilder_ == null) {
        ensureOrderOffersIsMutable();
        orderOffers_.remove(index);
        onChanged();
      } else {
        orderOffersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOffer.Builder getOrderOffersBuilder(
        int index) {
      return getOrderOffersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder getOrderOffersOrBuilder(
        int index) {
      if (orderOffersBuilder_ == null) {
        return orderOffers_.get(index);  } else {
        return orderOffersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public java.util.List<? extends mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder> 
         getOrderOffersOrBuilderList() {
      if (orderOffersBuilder_ != null) {
        return orderOffersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderOffers_);
      }
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOffer.Builder addOrderOffersBuilder() {
      return getOrderOffersFieldBuilder().addBuilder(
          mango.sep3.databaseaccess.protobuf.OrderOffer.getDefaultInstance());
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public mango.sep3.databaseaccess.protobuf.OrderOffer.Builder addOrderOffersBuilder(
        int index) {
      return getOrderOffersFieldBuilder().addBuilder(
          index, mango.sep3.databaseaccess.protobuf.OrderOffer.getDefaultInstance());
    }
    /**
     * <code>repeated .OrderOffer orderOffers = 1;</code>
     */
    public java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer.Builder> 
         getOrderOffersBuilderList() {
      return getOrderOffersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        mango.sep3.databaseaccess.protobuf.OrderOffer, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder, mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder> 
        getOrderOffersFieldBuilder() {
      if (orderOffersBuilder_ == null) {
        orderOffersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            mango.sep3.databaseaccess.protobuf.OrderOffer, mango.sep3.databaseaccess.protobuf.OrderOffer.Builder, mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder>(
                orderOffers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        orderOffers_ = null;
      }
      return orderOffersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OrderOffers)
  }

  // @@protoc_insertion_point(class_scope:OrderOffers)
  private static final mango.sep3.databaseaccess.protobuf.OrderOffers DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mango.sep3.databaseaccess.protobuf.OrderOffers();
  }

  public static mango.sep3.databaseaccess.protobuf.OrderOffers getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderOffers>
      PARSER = new com.google.protobuf.AbstractParser<OrderOffers>() {
    @java.lang.Override
    public OrderOffers parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderOffers(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderOffers> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderOffers> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public mango.sep3.databaseaccess.protobuf.OrderOffers getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

