// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  java.util.List<mango.sep3.databaseaccess.protobuf.OrderOffer> 
      getOrderOffersList();
  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  mango.sep3.databaseaccess.protobuf.OrderOffer getOrderOffers(int index);
  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  int getOrderOffersCount();
  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  java.util.List<? extends mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder> 
      getOrderOffersOrBuilderList();
  /**
   * <code>repeated .OrderOffer orderOffers = 2;</code>
   */
  mango.sep3.databaseaccess.protobuf.OrderOfferOrBuilder getOrderOffersOrBuilder(
      int index);

  /**
   * <code>bool isDone = 3;</code>
   * @return The isDone.
   */
  boolean getIsDone();

  /**
   * <code>string farmName = 4;</code>
   * @return The farmName.
   */
  java.lang.String getFarmName();
  /**
   * <code>string farmName = 4;</code>
   * @return The bytes for farmName.
   */
  com.google.protobuf.ByteString
      getFarmNameBytes();

  /**
   * <code>string collectionOption = 5;</code>
   * @return The collectionOption.
   */
  java.lang.String getCollectionOption();
  /**
   * <code>string collectionOption = 5;</code>
   * @return The bytes for collectionOption.
   */
  com.google.protobuf.ByteString
      getCollectionOptionBytes();
}
