// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

public interface OrderOfferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderOffer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.Offer offer = 2;</code>
   * @return Whether the offer field is set.
   */
  boolean hasOffer();
  /**
   * <code>.Offer offer = 2;</code>
   * @return The offer.
   */
  mango.sep3.databaseaccess.protobuf.Offer getOffer();
  /**
   * <code>.Offer offer = 2;</code>
   */
  mango.sep3.databaseaccess.protobuf.OfferOrBuilder getOfferOrBuilder();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string username = 4;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 4;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string collectionOption = 5;</code>
   * @return The collectionOption.
   */
  java.lang.String getCollectionOption();
  /**
   * <code>string collectionOption = 5;</code>
   * @return The bytes for collectionOption.
   */
  com.google.protobuf.ByteString
      getCollectionOptionBytes();
}
