// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package mango.sep3.databaseaccess.protobuf;

public interface OrdersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Orders)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Order orders = 1;</code>
   */
  java.util.List<mango.sep3.databaseaccess.protobuf.Order> 
      getOrdersList();
  /**
   * <code>repeated .Order orders = 1;</code>
   */
  mango.sep3.databaseaccess.protobuf.Order getOrders(int index);
  /**
   * <code>repeated .Order orders = 1;</code>
   */
  int getOrdersCount();
  /**
   * <code>repeated .Order orders = 1;</code>
   */
  java.util.List<? extends mango.sep3.databaseaccess.protobuf.OrderOrBuilder> 
      getOrdersOrBuilderList();
  /**
   * <code>repeated .Order orders = 1;</code>
   */
  mango.sep3.databaseaccess.protobuf.OrderOrBuilder getOrdersOrBuilder(
      int index);
}
